version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./flask_data:/code

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --appendonly yes
    volumes:
      - ./redis_data:/data

volumes:
  redis_data:
  compose: